### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by heyalexchoi** [o19s/elyzer#2]
hey, i'm getting some kind of import problem. maybe you can help?

running python 3.4.3 through pyenv

here's what i got after doing ```pip install elyzer```

```
elyzer --es "http://localhost:9200" --index companies --analyzer services_analyzer --text "coding"
Traceback (most recent call last):
  File "/Users/alexchoi/.pyenv/versions/3.4.3/bin/elyzer", line 9, in <module>
    load_entry_point('elyzer==0.1.1', 'console_scripts', 'elyzer')()
  File "/Users/alexchoi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/alexchoi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/Users/alexchoi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/Users/alexchoi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/alexchoi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/elyzer/__main__.py", line 3, in <module>
    from elyzer import stepWise, getAnalyzer
ImportError: cannot import name 'stepWise'
```

**Comment by softwaredoug** [comment]
Thanks, I need better testing around this library. I am working on this python 3 branch

https://github.com/o19s/elyzer/tree/python-3
