### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Idnan** [o19s/elyzer#8]
Hi, I got this error while running this command. I am using elasticsearch version 5.0.1

*Command*
```
elyzer --es "http://localhost:9200" --index index_name --analyzer analyzer_name --text "some string"
```

*Error:*
```
CHAR_FILTER: special_char_filter
Traceback (most recent call last):
  File "/usr/local/bin/elyzer", line 9, in <module>
    load_entry_point('elyzer==0.2.2', 'console_scripts', 'elyzer')()
  File "/usr/local/lib/python2.7/dist-packages/elyzer/__main__.py", line 30, in main
    es=es))
  File "/usr/local/lib/python2.7/dist-packages/elyzer/elyzer.py", line 65, in stepWise
    char_filters=",".join(charFiltersInUse))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 29, in analyze
    '_analyze'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 106, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'request [/autocomplete_ahs_index/_analyze] contains unrecognized parameter: [char_filters] -> did you mean [char_filter]?')
```

**Comment by timsweb** [comment]
Same problem using Elasticsearch 5.2.
```CHAR_FILTER: url_safe_1
Traceback (most recent call last):
  File "/Users/tim/Library/Python/2.7/bin/elyzer", line 11, in <module>
    sys.exit(main())
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elyzer/__main__.py", line 30, in main
    es=es))
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elyzer/elyzer.py", line 65, in stepWise
    char_filters=",".join(charFiltersInUse))
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elasticsearch/client/indices.py", line 29, in analyze
    '_analyze'), params=params, body=body)
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elasticsearch/connection/http_urllib3.py", line 106, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/tim/Library/Python/2.7/lib/python/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'request [/books_1/_analyze] contains unrecognized parameter: [char_filters] -> did you mean [char_filter]?')```

**Comment by softwaredoug** [comment]
Thanks to both of you. Sorry it took so long to resolve this. Version 0.3.3 supports Elasticsearch 5.x. Please confirm it works for you.

```
pip install elyzer==0.3.3
```
